version: "3.7"
services:
  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    ports:
      - 8000:8000
    environment:
      DB_NAME: sekigae
      DB_USER: fastapi
      DB_PASSWORD: fastapi
      DB_HOST: postgres
      DB_PORT: 5433
    links:
      - postgres
  postgres:
    image: postgres:12
    volumes:
      - pq_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: sekigae
    ports:
      - 5433:5432
volumes:
  pq_data:
