version: "3.7"
services:
  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    ports:
      - 8000:8000
    env_file: ./fastapi/fastapi.env
    depends_on:
      - postgres
  postgres:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./postgres/postgres.env
    ports:
      - 5432:5432
volumes:
  postgres_data: