"""add_firebase_uid_to_user

Revision ID: c2dc0f9395d6
Revises: e83620ce3aca
Create Date: 2022-01-01 13:20:11.874812+09:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2dc0f9395d6"
down_revision = "e83620ce3aca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("firebase_uid", sa.VARCHAR(length=128), nullable=True)
    )
    op.create_unique_constraint(None, "users", ["firebase_uid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "firebase_uid")
    # ### end Alembic commands ###
