"""student

Revision ID: d0c79969f425
Revises: 8bf6f6f70d43
Create Date: 2022-01-04 11:09:34.821871+09:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d0c79969f425"
down_revision = "8bf6f6f70d43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="登録日時",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            comment="最終更新日時",
        ),
        sa.Column("is_active", sa.BOOLEAN(), server_default="true", nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("number", sa.INTEGER(), nullable=False),
        sa.Column("student_sheet_uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.CheckConstraint("number > 0"),
        sa.ForeignKeyConstraint(
            ["student_sheet_uuid"], ["student_sheets.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("number", "student_sheet_uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("students")
    # ### end Alembic commands ###
